# Generated by Django 4.1 on 2022-09-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("employee_name", models.TextField()),
                ("employee_surname", models.TextField()),
                ("employee_hire_date", models.TextField()),
                ("employee_dni", models.TextField()),
                ("branch_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
            },
        ),
        migrations.CreateModel(
            name="DireccionEmpleado",
            fields=[
                ("id_direccion", models.AutoField(primary_key=True, serialize=False)),
                ("direccion", models.TextField()),
                ("ciudad", models.TextField()),
                ("provincia", models.TextField()),
                ("pais", models.TextField()),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Empleados.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dirección del empleado",
                "verbose_name_plural": "Direcciones de los empleados",
            },
        ),
    ]
