# Generated by Django 4.1 on 2022-09-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "registration",
            "0002_remove_usuario_email_remove_usuario_first_name_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Usuario",
        ),
    ]
