# Generated by Django 4.1 on 2022-09-06 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Cuentas", "0002_cuenta_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cuenta",
            name="username",
        ),
    ]
