# Generated by Django 4.1 on 2022-09-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("username", models.CharField(max_length=255)),
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_name", models.TextField()),
                ("customer_surname", models.TextField()),
                ("customer_DNI", models.IntegerField(blank=True, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("branch_id", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registration.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.CreateModel(
            name="DireccionCliente",
            fields=[
                ("id_direccion", models.AutoField(primary_key=True, serialize=False)),
                ("direccion", models.TextField()),
                ("ciudad", models.TextField()),
                ("provincia", models.TextField()),
                ("pais", models.TextField()),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Direccion del Cliente",
                "verbose_name_plural": "Direcciones de los Clientes",
            },
        ),
    ]
