# Generated by Django 4.1 on 2022-08-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_name", models.TextField()),
                ("customer_surname", models.TextField()),
                ("customer_dni", models.TextField(db_column="customer_DNI")),
                ("dob", models.TextField(blank=True, null=True)),
                ("branch_id", models.IntegerField()),
            ],
            options={
                "db_table": "cliente",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="AuthGroup",
        ),
        migrations.DeleteModel(
            name="AuthGroupPermissions",
        ),
        migrations.DeleteModel(
            name="AuthPermission",
        ),
        migrations.DeleteModel(
            name="AuthUser",
        ),
        migrations.DeleteModel(
            name="AuthUserGroups",
        ),
        migrations.DeleteModel(
            name="AuthUserUserPermissions",
        ),
        migrations.DeleteModel(
            name="DjangoAdminLog",
        ),
        migrations.DeleteModel(
            name="DjangoContentType",
        ),
        migrations.DeleteModel(
            name="DjangoMigrations",
        ),
        migrations.DeleteModel(
            name="DjangoSession",
        ),
    ]
