# Generated by Django 4.1 on 2022-09-06 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Clientes", "0002_alter_cliente_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="username",
        ),
    ]
