# Generated by Django 4.1 on 2022-09-06 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Clientes", "0004_alter_cliente_customer_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="direccioncliente",
            name="customer_id",
        ),
        migrations.AddField(
            model_name="direccioncliente",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
