# Generated by Django 4.1 on 2022-09-07 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Clientes", "0007_alter_cliente_branch_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="branch_id",
        ),
    ]
