# Generated by Django 4.1 on 2022-09-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tarjetas",
            fields=[
                ("numero", models.TextField(primary_key=True, serialize=False)),
                ("cvv", models.TextField()),
                ("fecha_de_otorgamiento", models.TextField()),
                ("fecha_de_vencimiento", models.TextField()),
                ("tipo_de_tarjeta", models.TextField()),
                ("marca_tarjetas", models.TextField(default="VISA")),
            ],
            options={
                "verbose_name": "Tarjeta",
                "verbose_name_plural": "Tarjetas",
            },
        ),
    ]
