# Generated by Django 4.1 on 2022-09-06 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Tarjetas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarjetas",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tarjetas",
            name="cvv",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="tarjetas",
            name="fecha_de_otorgamiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tarjetas",
            name="fecha_de_vencimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tarjetas",
            name="marca_tarjetas",
            field=models.CharField(default="VISA", max_length=30),
        ),
        migrations.AlterField(
            model_name="tarjetas",
            name="numero",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tarjetas",
            name="tipo_de_tarjeta",
            field=models.CharField(max_length=30),
        ),
    ]
