# Generated by Django 4.1 on 2022-09-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0002_tarjetas_user_alter_tarjetas_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetas',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='tarjetas',
            name='numero',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
