# Generated by Django 4.1 on 2022-09-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                ("loan_id", models.AutoField(primary_key=True, serialize=False)),
                ("loan_type", models.TextField()),
                ("loan_date", models.TextField()),
                ("loan_total", models.IntegerField()),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestamo",
                "verbose_name_plural": "Prestamos",
            },
        ),
    ]
