# Generated by Django 4.1 on 2022-09-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Prestamos", "0002_remove_prestamo_customer_id_prestamo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestamo",
            name="loan_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
