# Generated by Django 4.1 on 2022-09-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Prestamos", "0003_alter_prestamo_loan_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestamo",
            name="loan_type",
            field=models.CharField(max_length=30),
        ),
    ]
