# Generated by Django 4.1 on 2022-09-06 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Prestamos", "0005_prestamo_branch_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prestamo",
            old_name="branch_name",
            new_name="branch_id",
        ),
    ]
