# Generated by Django 4.1 on 2022-09-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0006_rename_branch_name_prestamo_branch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='branch_id',
        ),
    ]
