# Generated by Django 4.1 on 2022-09-07 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursales', '0004_remove_sucursal_loan_id'),
        ('Prestamos', '0008_prestamo_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sucursales.sucursal'),
        ),
    ]
