# Generated by Django 4.1 on 2022-09-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                ("branch_id", models.IntegerField(primary_key=True, serialize=False)),
                ("branch_number", models.BinaryField()),
                ("branch_name", models.TextField()),
                ("branch_address_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "Sucursal",
                "verbose_name_plural": "Sucursales",
            },
        ),
    ]
