# Generated by Django 4.1 on 2022-09-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sucursales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sucursal",
            name="branch_name",
            field=models.CharField(max_length=30),
        ),
    ]
