# Generated by Django 4.1 on 2022-09-06 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Prestamos", "0005_prestamo_branch_name"),
        ("Sucursales", "0002_alter_sucursal_branch_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sucursal",
            name="loan_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Prestamos.prestamo",
            ),
            preserve_default=False,
        ),
    ]
