# Generated by Django 4.1 on 2022-09-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sucursales", "0004_remove_sucursal_loan_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sucursal",
            name="branch_address_id",
        ),
        migrations.RemoveField(
            model_name="sucursal",
            name="branch_number",
        ),
        migrations.AlterField(
            model_name="sucursal",
            name="branch_name",
            field=models.CharField(
                choices=[("1", "Almagro (1)"), ("2", "Caballito (2)")], max_length=30
            ),
        ),
    ]
