# Generated by Django 4.1 on 2022-09-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sucursales", "0006_alter_sucursal_branch_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sucursal",
            name="branch_name",
            field=models.CharField(
                choices=[("Almagro", "1"), ("Caballito", "2")], max_length=30
            ),
        ),
    ]
